version: "3.7"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "db"
      - "server"
    volumes:
      - ./web:/app:rw
    stdin_open: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - "db"
    volumes:
      - ./server:/app:rw